apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"
  MYSQL_USER: "YXBwX3VzZXI=" # Base64 encoding for "app_user"
  MYSQL_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"
