apiVersion: v1
kind: Service
metadata:
  name: kube-controller-manager-http
  namespace: kube-system
spec:
  selector:
    app: kube-controller-manager-proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
