apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager-proxy
  namespace: kube-system
spec:
  containers:
  - name: kube-controller-manager-proxy
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  volumes:
  - name: nginx-config
    configMap:
      name: kube-controller-manager-proxy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-controller-manager-proxy-config
  namespace: kube-system
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          proxy_pass https://kube-controller-manager-kind-control-plane:10257;
          proxy_ssl_verify off;
        }
      }
    }
