kind: ServiceAccount
apiVersion: v1
metadata:
  name: secrets-reader
  namespace: todoapp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: todoapp
  name: secrets-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-reader-binding
  namespace: todoapp
subjects:
- kind: ServiceAccount
  name: secrets-reader
roleRef:
  kind: Role
  name: secrets-reader
  apiGroup: rbac.authorization.k8s.io