apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.todoapp.secret.SECRET_KEY | b64enc}}
  DB_NAME: {{ .Values.todoapp.secret.DB_NAME | b64enc}}
  DB_USER: {{ .Values.todoapp.secret.DB_USER | b64enc}}
  DB_PASSWORD: {{ .Values.todoapp.secret.DB_PASSWORD | b64enc}}
  DB_HOST: {{ .Values.todoapp.secret.DB_HOST | b64enc}}
