apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    job: todoapp-job
    app: todoapp
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
