apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-servicemonitor
  namespace: todoapp
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: todoapp
  endpoints:
    - port: {{ .Values.serviceMonitor.port}}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
