apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name}}
  namespace: {{ .Values.namespace}}
  labels:
    app: mysql
data:
  init.sql: |
    GRANT ALL PRIVILEGES ON app_db.* TO 'app-user'@'%';
    USE app_db;
    CREATE TABLE counter (
        id INT AUTO_INCREMENT PRIMARY KEY,
        value INT
    );
