apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name}}-secrets
  namespace: {{ .Values.namespace}}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secrets.MYSQL_ROOT_PASSWORD | b64enc}}
  MYSQL_USER: {{ .Values.mysql.secrets.MYSQL_USER | b64enc}}
  MYSQL_PASSWORD: {{ .Values.mysql.secrets.MYSQL_PASSWORD | b64enc}}
  MYSQL_DATABASE: {{ .Values.mysql.secrets.MYSQL_DATABASE | b64enc}}
