apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.mysql.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.mysql.secrets }}
    {{ $key | upper }}: {{ $value }}
  {{- end }}
