mysql:
  namespace: mysql
  image:
    repository: mysql
    tag: 8.0
  replicas: 2
  port: 3306

  service:
    clusterIP: None

  secrets:
    MYSQL_ROOT_PASSWORD: "MTIzNA=="
    MYSQL_USER: "YXBwX3VzZXI="
    MYSQL_PASSWORD: "MTIzNA=="
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  storage:
    size: "2Gi"

  tolerations:
    - key: "app"
      operator: "Equal"
      value: "mysql"
      effect: "NoSchedule"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app"
                operator: In
                values:
                - mysql
          topologyKey: "kubernetes.io/hostname"
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - nodeSelectorTerms:
            - matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - "mysql"
