mysql:
  namespace:
    name: mysql

  secrets:
    MYSQL_ROOT_PASSWORD: "1234"
    MYSQL_USER: app_user
    MYSQL_PASSWORD: "1234"

  replicas:
    qty: 1

  containers:
    repository: mysql
    tag: 8.0

  pvc:
    storage: 2Gi

  resources:
      cpu: "256m"
      memory: "500Mi"

  tolerations:
    key: "app"
    value: "mysql"

  affinity:
    podaffinity:
      key: "app"
      value:
      - mysql
    nodeaffinity:
      key: "app"
      value:
      - "mysql"
