apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todoapp-servicemonitor
  namespace: todoapp
  labels:
    app: todoapp
    release: prometheus
spec:
  selector:
    matchLabels:
      app: todoapp
  endpoints:
  - interval: 10s
    path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - todoapp
