apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Values.todoapp.namespace }}
spec:
  replicas: {{ .Values.todoapp.replicaCount | default 1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.todoapp.rollingUpdate.maxSurge | default 1 }}
      maxUnavailable: {{ .Values.todoapp.rollingUpdate.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-secrets-reader
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.todoapp.image.repository }}:{{ .Values.todoapp.image.tag }}"
        ports:
        - containerPort: {{ .Values.todoapp.service.targetPort }}
        env:
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: PYTHONUNBUFFERED
        {{- range $key, $value := .Values.todoapp.secrets }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: todoapp-secret
              key: {{ $key }}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.todoapp.resources.requests.memory }}
            cpu: {{ .Values.todoapp.resources.requests.cpu }}
          limits:
            memory: {{ .Values.todoapp.resources.limits.memory }}
            cpu: {{ .Values.todoapp.resources.limits.cpu }}
        livenessProbe:
          {{- toYaml .Values.todoapp.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.todoapp.readinessProbe | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: app-secrets-volume
          mountPath: /app/secrets
          readOnly: true
        - name: app-config-volume
          mountPath: /app/configs
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-pvc-data
      - name: app-secrets-volume
        secret:
          secretName: {{ .Chart.Name }}-secret
      - name: app-config-volume
        configMap:
          name: {{ .Chart.Name }}-config
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: app
                operator: In
                values:
                - kube2py
