apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nodeport
  namespace: {{ .Values.todoapp.namespace }}
  labels:
    job: {{ .Chart.Name }}-job
    app: {{ .Chart.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: {{ .Values.todoapp.serviceMonitor.port }}
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30007
