apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc-data
  namespace: {{ .Values.todoapp.namespace }}
spec:
  volumeName: {{ .Chart.Name }}-pv-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.todoapp.volumes.persistentVolumeClaim.requestStorage }}
