apiVersion: v1
kind: Secret
metadata:
 name: {{ .Chart.Name }}-secret
 namespace: {{ .Values.todoapp.namespace }}
type: Opaque
data:
{{- range $key, $val:= .Values.todoapp.secrets }}
 {{ $key | upper }}: {{ $val }}
{{- end }}
