{{- if .Values.todoapp.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-service-monitor
  labels:
    app: {{ .Chart.Name }}
    release: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  endpoints:
    - interval: {{ .Values.todoapp.serviceMonitor.interval }}
      port: {{ .Values.todoapp.serviceMonitor.port }}
      path: {{ .Values.todoapp.serviceMonitor.path }}
{{- end -}}
